version: 2.1

orbs:
  node: circleci/node@4.7.0
  slack: circleci/slack@4.4.4
jobs:
  build_and_deploy_mainnet:
    resource_class: large
    docker:
      - image: 'cimg/node:16.7'
    steps:
      - checkout
      - run:
          name: download & unzip awscli v2
          command: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip
      - run:
          name: install awscli v2
          command: sudo ./aws/install
      - restore_cache:
          key: uninfo-deps-{{ checksum "package.json" }}
      - run:
          name: install yarn dependencies
          command: yarn
      - save_cache:
          key: uninfo-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: production build
          command: CI=false NODE_ENV=production yarn build
      - run:
          name: s3 sync
          command: aws s3 sync ./build/ s3://info.voltswap/ --delete --acl public-read
      - run:
          name: invalidation
          command: aws cloudfront create-invalidation --distribution-id EQKL5C4QOPA6I --paths "/*"
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
workflows:
  fresh_deploy:
    jobs:
      - build_and_deploy_mainnet:
          context:
            - new-aws-s3
            - slack-secrets
            - uniswap-info-env
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
